/**
 * Class progression table specs for the D&D 5e SRD 5.1 importer (eshyra-4a7.6).
 *
 * Every base class prints a level-progression table (`The Bard` … `The
 * Wizard`), and two class features own their own reference tables (the Druid's
 * `Beast Shapes`, the Cleric's `Destroy Undead`). These are emitted as
 * document-wide `table` records through `parseDocumentTables`, sharing its
 * typography-anchored location and exact row-count coverage gate
 * (`EXPECTED_SRD_5_1_TABLE_NAMES`). Structured per-level class data
 * (`class.data.progression`) is a separate follow-up; this module only
 * preserves the source tables as reviewed `table` records.
 *
 * Three shapes appear here:
 *
 *   - Barbarian (in `parseDocumentTables.ts`, not this module) and the two
 *     martial classes Fighter and Rogue extract as one contiguous cell-tier
 *     run right after the caption, so they use the algorithmic
 *     `wrapped-last-column` rule (their wrapping Features cell is the last
 *     column).
 *   - The other nine class tables are sheared by the two-column page layout
 *     into separate cell-tier runs interleaved with the proficiency/Equipment
 *     prose; they use `class-progression-reconstruction`, which pins the exact
 *     contiguous source block(s) and carries the reviewed row reconstruction.
 *   - `Beast Shapes` (wrapped Limitations/Example cells over three rows) uses
 *     `reviewed-reconstruction`; `Destroy Undead` is a clean five-row
 *     `line-per-row` table.
 *
 * The reconstruction `rows` were derived from the vendored SRD PDF and verified
 * against the printed tables (cantrips/spells known, spell-slot progression,
 * class resources such as Rages, Sneak Attack, Ki Points, Sorcery Points, and
 * Pact Magic slots). Source tokens are preserved verbatim ("+2", "1d6",
 * "Unlimited", "+10 ft.", lost apostrophes like "Land s Stride"). The pinned
 * `sourceBlocks` make any re-extraction drift fail the table closed.
 *
 * Blank vs. dash cells (verified against the source text layer): SRD 5.1 leaves
 * an unavailable cell BLANK — it does NOT print a dash there. Across the whole
 * Classes chapter the only genuine table-cell em dashes are the Monk's level-1
 * Ki Points and Unarmored Movement ("1st +2 1d4 — —") and the Beast Shapes
 * level-8 Limitations cell ("8th 1 — Giant"); those are emitted as "—". Every
 * unavailable spell-slot cell and every empty Features row (e.g. Bard levels 7
 * and 11, Cleric level 3, the Paladin/Ranger half-caster slots before they come
 * online) carries no glyph in the source — the columns are simply blank, and
 * the rows extract with VARIABLE token counts — so they are emitted as "" rather
 * than a fabricated "—" (ADR 0007: the importer never supplies a token the
 * source does not print). The regression tests in srdGeneratedPack.test.ts pin
 * both conventions so a future change that fabricates or drops a dash fails
 * loudly.
 */

import type { DocumentTableSpec } from './parseDocumentTables.js';

const ORDINAL = String.raw`\d{1,2}(?:st|nd|rd|th)`;

/**
 * The two martial class tables whose columns share one physical line per row
 * (like the Barbarian), with the Features text wrapping onto continuation
 * cell lines that re-join into the last column.
 */
const FIGHTER_AND_ROGUE_SPECS: readonly DocumentTableSpec[] = [
  {
    name: 'The Fighter',
    columns: ['Level', 'Proficiency Bonus', 'Features'],
    anchorHeading: 'The Fighter',
    anchor: 'caption',
    headerLines: ['Proficiency', 'Level Bonus Features'],
    rows: {
      kind: 'wrapped-last-column',
      start: new RegExp(`^(${ORDINAL})\\s+(\\+\\d)\\s+(.+)$`),
    },
    expectedRows: 20,
  },
  {
    name: 'The Rogue',
    columns: ['Level', 'Proficiency Bonus', 'Sneak Attack', 'Features'],
    anchorHeading: 'The Rogue',
    anchor: 'caption',
    headerLines: ['Proficiency Sneak', 'Level Bonus Attack Features'],
    rows: {
      kind: 'wrapped-last-column',
      start: new RegExp(`^(${ORDINAL})\\s+(\\+\\d)\\s+(\\d+d\\d+)\\s+(.+)$`),
    },
    expectedRows: 20,
  },
];

/**
 * Two feature-owned reference tables in the class chapters. `Beast Shapes`
 * (Druid Wild Shape, p20) wraps its Limitations and Example cells across three
 * rows; `Destroy Undead` (Cleric, p17) is a clean five-row table whose caption
 * collides with the `feature:cleric:destroy-undead` heading — the source
 * coverage maps the caption to this table explicitly.
 */
const FEATURE_OWNED_TABLE_SPECS: readonly DocumentTableSpec[] = [
  {
    name: 'Beast Shapes',
    columns: ['Level', 'Max. CR', 'Limitations', 'Example'],
    anchorHeading: 'Beast Shapes',
    anchor: 'caption',
    headerLines: ['Max.', 'Level CR Limitations Example'],
    rows: {
      kind: 'reviewed-reconstruction',
      sourceLines: [
        '2nd 1/4 No flying or swimming Wolf',
        'speed',
        '4th 1/2 No flying speed Crocodile',
        '8th 1 — Giant',
        'eagle',
      ],
      rows: [
        ['2nd', '1/4', 'No flying or swimming speed', 'Wolf'],
        ['4th', '1/2', 'No flying speed', 'Crocodile'],
        ['8th', '1', '—', 'Giant eagle'],
      ],
    },
    expectedRows: 3,
  },
  {
    name: 'Destroy Undead',
    columns: ['Cleric Level', 'Destroys Undead of CR . . .'],
    anchorHeading: 'Destroy Undead',
    anchor: 'caption',
    headerLines: ['Cleric Level Destroys Undead of CR . . .'],
    rows: {
      kind: 'line-per-row',
      pattern: new RegExp(`^(${ORDINAL}) (.+)$`),
    },
    expectedRows: 5,
  },
];

/**
 * The nine class progression tables sheared into separate cell-tier runs by
 * the two-column layout, reconstructed from pinned source blocks (verified
 * against the SRD print). See the module header.
 */
const RECONSTRUCTED_CLASS_PROGRESSION_SPECS: readonly DocumentTableSpec[] = [
  {
    name: 'The Bard',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      'Cantrips Known',
      'Spells Known',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
      '6th',
      '7th',
      '8th',
      '9th',
    ],
    anchorHeading: 'The Bard',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          '—Spell Slots per Spell Level—',
          'Level Bonus Features Known',
          '1st +2 Spellcasting, Bardic Inspiration',
          '(d6)',
          '2nd +2 Jack of All Trades, Song of Rest',
          '(d6)',
          '3rd +2 Bard College, Expertise',
          '4th +2 Ability Score Improvement',
          '5th +3 Bardic Inspiration (d8), Font of',
          'Inspiration',
          '6th +3 Countercharm, Bard College',
          'feature',
          '7th +3',
          '8th +3 Ability Score Improvement',
          '9th +4 Song of Rest (d8)',
          '10th +4 Bardic Inspiration (d10),',
          'Expertise, Magical Secrets',
          '11th +4',
          '12th +4 Ability Score Improvement',
          '13th +5 Song of Rest (d10)',
          '14th +5 Magical Secrets, Bard College',
          'feature',
          '15th +5 Bardic Inspiration (d12)',
          '16th +5 Ability Score Improvement',
          '17th +6 Song of Rest (d12)',
          '18th +6 Magical Secrets',
          '19th +6 Ability Score Improvement',
          '20th +6 Superior Inspiration',
          'Known 1st 2nd 3rd 4th 5th 6th 7th 8th 9th',
          '2 4 2',
          '2 5 3',
          '2 6 4 2',
          '3 7 4 3',
          '3 8 4 3 2',
          '3 9 4 3 3',
          '3 10 4 3 3 1',
          '3 11 4 3 3 2',
          '3 12 4 3 3 3 1',
          '4 14 4 3 3 3 2',
          '4 15 4 3 3 3 2 1',
          '4 15 4 3 3 3 2 1',
          '4 16 4 3 3 3 2 1 1',
          '4 18 4 3 3 3 2 1 1',
          '4 19 4 3 3 3 2 1 1 1',
          '4 19 4 3 3 3 2 1 1 1',
          '4 20 4 3 3 3 2 1 1 1 1',
          '4 22 4 3 3 3 3 1 1 1 1',
          '4 22 4 3 3 3 3 2 1 1 1',
          '4 22 4 3 3 3 3 2 2 1 1',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          'Spellcasting, Bardic Inspiration (d6)',
          '2',
          '4',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '2nd',
          '+2',
          'Jack of All Trades, Song of Rest (d6)',
          '2',
          '5',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '3rd',
          '+2',
          'Bard College, Expertise',
          '2',
          '6',
          '4',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '4th',
          '+2',
          'Ability Score Improvement',
          '3',
          '7',
          '4',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '5th',
          '+3',
          'Bardic Inspiration (d8), Font of Inspiration',
          '3',
          '8',
          '4',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '6th',
          '+3',
          'Countercharm, Bard College feature',
          '3',
          '9',
          '4',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['7th', '+3', '', '3', '10', '4', '3', '3', '1', '', '', '', '', ''],
        [
          '8th',
          '+3',
          'Ability Score Improvement',
          '3',
          '11',
          '4',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '9th',
          '+4',
          'Song of Rest (d8)',
          '3',
          '12',
          '4',
          '3',
          '3',
          '3',
          '1',
          '',
          '',
          '',
          '',
        ],
        [
          '10th',
          '+4',
          'Bardic Inspiration (d10), Expertise, Magical Secrets',
          '4',
          '14',
          '4',
          '3',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
        ],
        ['11th', '+4', '', '4', '15', '4', '3', '3', '3', '2', '1', '', '', ''],
        [
          '12th',
          '+4',
          'Ability Score Improvement',
          '4',
          '15',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        [
          '13th',
          '+5',
          'Song of Rest (d10)',
          '4',
          '16',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        [
          '14th',
          '+5',
          'Magical Secrets, Bard College feature',
          '4',
          '18',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        [
          '15th',
          '+5',
          'Bardic Inspiration (d12)',
          '4',
          '19',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        [
          '16th',
          '+5',
          'Ability Score Improvement',
          '4',
          '19',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        [
          '17th',
          '+6',
          'Song of Rest (d12)',
          '4',
          '20',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '18th',
          '+6',
          'Magical Secrets',
          '4',
          '22',
          '4',
          '3',
          '3',
          '3',
          '3',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '19th',
          '+6',
          'Ability Score Improvement',
          '4',
          '22',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
        ],
        [
          '20th',
          '+6',
          'Superior Inspiration',
          '4',
          '22',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '2',
          '1',
          '1',
        ],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Cleric',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      'Cantrips Known',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
      '6th',
      '7th',
      '8th',
      '9th',
    ],
    anchorHeading: 'The Cleric',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Spell Slots per Spell Level',
          '1st 2nd 3rd 4th 5th 6th 7th 8th 9th',
          '1st +2 Spellcasting, Divine Domain',
          '2nd +2 Channel Divinity (1/rest), Divine Domain',
          'feature',
          '3rd +2',
          '4th +2 Ability Score Improvement',
          '5th +3 Destroy Undead (CR 1/2)',
          '6th +3 Channel Divinity (2/rest), Divine Domain',
          'feature',
          '7th +3',
          '8th +3 Ability Score Improvement, Destroy Undead',
          '(CR 1), Divine Domain feature',
          '9th +4',
          '10th +4 Divine Intervention',
          '11th +4 Destroy Undead (CR 2)',
          '12th +4 Ability Score Improvement',
          '13th +5',
          '14th +5 Destroy Undead (CR 3)',
          '15th +5',
          '16th +5 Ability Score Improvement',
          '17th +6 Destroy Undead (CR 4), Divine Domain',
          'feature',
          '18th +6 Channel Divinity (3/rest)',
          '19th +6 Ability Score Improvement',
          '20th +6 Divine Intervention improvement',
          '3 2',
          '3 3',
          '3 4 2',
          '4 4 3',
          '4 4 3 2',
          '4 4 3 3',
          '4 4 3 3 1',
          '4 4 3 3 2',
          '4 4 3 3 3 1',
          '5 4 3 3 3 2',
          '5 4 3 3 3 2 1',
          '5 4 3 3 3 2 1',
          '5 4 3 3 3 2 1 1',
          '5 4 3 3 3 2 1 1',
          '5 4 3 3 3 2 1 1 1',
          '5 4 3 3 3 2 1 1 1',
          '5 4 3 3 3 2 1 1 1 1',
          '5 4 3 3 3 3 1 1 1 1',
          '5 4 3 3 3 3 2 1 1 1',
          '5 4 3 3 3 3 2 2 1 1',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          'Spellcasting, Divine Domain',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '2nd',
          '+2',
          'Channel Divinity (1/rest), Divine Domain feature',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['3rd', '+2', '', '3', '4', '2', '', '', '', '', '', '', ''],
        [
          '4th',
          '+2',
          'Ability Score Improvement',
          '4',
          '4',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '5th',
          '+3',
          'Destroy Undead (CR 1/2)',
          '4',
          '4',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '6th',
          '+3',
          'Channel Divinity (2/rest), Divine Domain feature',
          '4',
          '4',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['7th', '+3', '', '4', '4', '3', '3', '1', '', '', '', '', ''],
        [
          '8th',
          '+3',
          'Ability Score Improvement, Destroy Undead (CR 1), Divine Domain feature',
          '4',
          '4',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
        ],
        ['9th', '+4', '', '4', '4', '3', '3', '3', '1', '', '', '', ''],
        [
          '10th',
          '+4',
          'Divine Intervention',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
        ],
        [
          '11th',
          '+4',
          'Destroy Undead (CR 2)',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        [
          '12th',
          '+4',
          'Ability Score Improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        ['13th', '+5', '', '5', '4', '3', '3', '3', '2', '1', '1', '', ''],
        [
          '14th',
          '+5',
          'Destroy Undead (CR 3)',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        ['15th', '+5', '', '5', '4', '3', '3', '3', '2', '1', '1', '1', ''],
        [
          '16th',
          '+5',
          'Ability Score Improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        [
          '17th',
          '+6',
          'Destroy Undead (CR 4), Divine Domain feature',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '18th',
          '+6',
          'Channel Divinity (3/rest)',
          '5',
          '4',
          '3',
          '3',
          '3',
          '3',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '19th',
          '+6',
          'Ability Score Improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
        ],
        [
          '20th',
          '+6',
          'Divine Intervention improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '2',
          '1',
          '1',
        ],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Druid',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      'Cantrips Known',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
      '6th',
      '7th',
      '8th',
      '9th',
    ],
    anchorHeading: 'The Druid',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Spell Slots per Spell Level',
          '1st 2nd 3rd 4th 5th 6th 7th 8th 9th',
          '1st +2 Druidic, Spellcasting',
          '2nd +2 Wild Shape, Druid Circle',
          '3rd +2',
          '4th +2 Wild Shape improvement, Ability Score',
          'Improvement',
          '5th +3',
          '6th +3 Druid Circle feature',
          '7th +3',
          '8th +3 Wild Shape improvement, Ability Score',
          'Improvement',
          '9th +4',
          '10th +4 Druid Circle feature',
          '11th +4',
          '12th +4 Ability Score Improvement',
          '13th +5',
          '14th +5 Druid Circle feature',
          '15th +5',
          '16th +5 Ability Score Improvement',
          '17th +6',
          '18th +6 Timeless Body, Beast Spells',
          '19th +6 Ability Score Improvement',
          '20th +6 Archdruid',
          '2 2',
          '2 3',
          '2 4 2',
          '3 4 3',
          '3 4 3 2',
          '3 4 3 3',
          '3 4 3 3 1',
          '3 4 3 3 2',
          '3 4 3 3 3 1',
          '4 4 3 3 3 2',
          '4 4 3 3 3 2 1',
          '4 4 3 3 3 2 1',
          '4 4 3 3 3 2 1 1',
          '4 4 3 3 3 2 1 1',
          '4 4 3 3 3 2 1 1 1',
          '4 4 3 3 3 2 1 1 1',
          '4 4 3 3 3 2 1 1 1 1',
          '4 4 3 3 3 3 1 1 1 1',
          '4 4 3 3 3 3 2 1 1 1',
          '4 4 3 3 3 3 2 2 1 1',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          'Druidic, Spellcasting',
          '2',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '2nd',
          '+2',
          'Wild Shape, Druid Circle',
          '2',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['3rd', '+2', '', '2', '4', '2', '', '', '', '', '', '', ''],
        [
          '4th',
          '+2',
          'Wild Shape improvement, Ability Score Improvement',
          '3',
          '4',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['5th', '+3', '', '3', '4', '3', '2', '', '', '', '', '', ''],
        [
          '6th',
          '+3',
          'Druid Circle feature',
          '3',
          '4',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['7th', '+3', '', '3', '4', '3', '3', '1', '', '', '', '', ''],
        [
          '8th',
          '+3',
          'Wild Shape improvement, Ability Score Improvement',
          '3',
          '4',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
        ],
        ['9th', '+4', '', '3', '4', '3', '3', '3', '1', '', '', '', ''],
        [
          '10th',
          '+4',
          'Druid Circle feature',
          '4',
          '4',
          '3',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
        ],
        ['11th', '+4', '', '4', '4', '3', '3', '3', '2', '1', '', '', ''],
        [
          '12th',
          '+4',
          'Ability Score Improvement',
          '4',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        ['13th', '+5', '', '4', '4', '3', '3', '3', '2', '1', '1', '', ''],
        [
          '14th',
          '+5',
          'Druid Circle feature',
          '4',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        ['15th', '+5', '', '4', '4', '3', '3', '3', '2', '1', '1', '1', ''],
        [
          '16th',
          '+5',
          'Ability Score Improvement',
          '4',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        ['17th', '+6', '', '4', '4', '3', '3', '3', '2', '1', '1', '1', '1'],
        [
          '18th',
          '+6',
          'Timeless Body, Beast Spells',
          '4',
          '4',
          '3',
          '3',
          '3',
          '3',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '19th',
          '+6',
          'Ability Score Improvement',
          '4',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
        ],
        [
          '20th',
          '+6',
          'Archdruid',
          '4',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '2',
          '1',
          '1',
        ],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Wizard',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      'Cantrips Known',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
      '6th',
      '7th',
      '8th',
      '9th',
    ],
    anchorHeading: 'The Wizard',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          '—Spell Slots per Spell Level—',
          '3rd 4th 5th 6th 7th 8th 9th',
          '1st +2 Spellcasting, Arcane Recovery',
          '2nd +2 Arcane Tradition',
          '3rd +2',
          '4th +2 Ability Score Improvement',
          '5th +3',
          '6th +3 Arcane Tradition feature',
          '7th +3',
          '8th +3 Ability Score Improvement',
          '9th +4',
          '10th +4 Arcane Tradition feature',
          '11th +4',
          '12th +4 Ability Score Improvement',
          '13th +5',
          '14th +5 Arcane Tradition feature',
          '15th +5',
          '16th +5 Ability Score Improvement',
          '17th +6',
          '18th +6 Spell Mastery',
          '19th +6 Ability Score Improvement',
          '20th +6 Signature Spell',
          '3 2',
          '3 3',
          '3 4 2',
          '4 4 3',
          '4 4 3 2',
          '4 4 3 3',
          '4 4 3 3 1',
          '4 4 3 3 2',
          '4 4 3 3 3 1',
          '5 4 3 3 3 2',
          '5 4 3 3 3 2 1',
          '5 4 3 3 3 2 1',
          '5 4 3 3 3 2 1 1',
          '5 4 3 3 3 2 1 1',
          '5 4 3 3 3 2 1 1 1',
          '5 4 3 3 3 2 1 1 1',
          '5 4 3 3 3 2 1 1 1 1',
          '5 4 3 3 3 3 1 1 1 1',
          '5 4 3 3 3 3 2 1 1 1',
          '5 4 3 3 3 3 2 2 1 1',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          'Spellcasting, Arcane Recovery',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '2nd',
          '+2',
          'Arcane Tradition',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['3rd', '+2', '', '3', '4', '2', '', '', '', '', '', '', ''],
        [
          '4th',
          '+2',
          'Ability Score Improvement',
          '4',
          '4',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['5th', '+3', '', '4', '4', '3', '2', '', '', '', '', '', ''],
        [
          '6th',
          '+3',
          'Arcane Tradition feature',
          '4',
          '4',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['7th', '+3', '', '4', '4', '3', '3', '1', '', '', '', '', ''],
        [
          '8th',
          '+3',
          'Ability Score Improvement',
          '4',
          '4',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
        ],
        ['9th', '+4', '', '4', '4', '3', '3', '3', '1', '', '', '', ''],
        [
          '10th',
          '+4',
          'Arcane Tradition feature',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
        ],
        ['11th', '+4', '', '5', '4', '3', '3', '3', '2', '1', '', '', ''],
        [
          '12th',
          '+4',
          'Ability Score Improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        ['13th', '+5', '', '5', '4', '3', '3', '3', '2', '1', '1', '', ''],
        [
          '14th',
          '+5',
          'Arcane Tradition feature',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        ['15th', '+5', '', '5', '4', '3', '3', '3', '2', '1', '1', '1', ''],
        [
          '16th',
          '+5',
          'Ability Score Improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        ['17th', '+6', '', '5', '4', '3', '3', '3', '2', '1', '1', '1', '1'],
        [
          '18th',
          '+6',
          'Spell Mastery',
          '5',
          '4',
          '3',
          '3',
          '3',
          '3',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '19th',
          '+6',
          'Ability Score Improvement',
          '5',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
        ],
        [
          '20th',
          '+6',
          'Signature Spell',
          '5',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '2',
          '1',
          '1',
        ],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Sorcerer',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Sorcery Points',
      'Features',
      'Cantrips Known',
      'Spells Known',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
      '6th',
      '7th',
      '8th',
      '9th',
    ],
    anchorHeading: 'The Sorcerer',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Proficiency Sorcery Cantrips',
          'Level Bonus Points Features Known',
          '1st +2 Spellcasting, Sorcerous',
          'Origin',
          '2nd +2 2 Font of Magic',
          '3rd +2 3 Metamagic',
          '4th +2 4 Ability Score',
          'Improvement',
          '5th +3 5',
          '6th +3 6 Sorcerous Origin',
          'feature',
          '7th +3 7',
          '8th +3 8 Ability Score',
          'Improvement',
          '9th +4 9',
          '10th +4 10 Metamagic',
          '11th +4 11',
          '12th +4 12 Ability Score',
          'Improvement',
          '13th +5 13',
          '14th +5 14 Sorcerous Origin',
          'feature',
          '15th +5 15',
          '16th +5 16 Ability Score',
          'Improvement',
          '17th +6 17 Metamagic',
          '18th +6 18 Sorcerous Origin',
          'feature',
          '19th +6 19 Ability Score',
          'Improvement',
          '20th +6 20 Sorcerous Restoration',
        ],
        [
          'Spells —Spell Slots per Spell Level—',
          'Known 1st 2nd 3rd 4th 5th 6th 7th 8th 9th',
          '4 2 2',
          '4 3 3',
          '4 4 4 2',
          '5 5 4 3',
          '5 6 4 3 2',
          '5 7 4 3 3',
          '5 8 4 3 3 1',
          '5 9 4 3 3 2',
          '5 10 4 3 3 3 1',
          '6 11 4 3 3 3 2',
          '6 12 4 3 3 3 2 1',
          '6 12 4 3 3 3 2 1',
          '6 13 4 3 3 3 2 1 1',
          '6 13 4 3 3 3 2 1 1',
          '6 14 4 3 3 3 2 1 1 1',
          '6 14 4 3 3 3 2 1 1 1',
          '6 15 4 3 3 3 2 1 1 1 1',
          '6 15 4 3 3 3 3 1 1 1 1',
          '6 15 4 3 3 3 3 2 1 1 1',
          '6 15 4 3 3 3 3 2 2 1 1',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          '',
          'Spellcasting, Sorcerous Origin',
          '4',
          '2',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '2nd',
          '+2',
          '2',
          'Font of Magic',
          '4',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '3rd',
          '+2',
          '3',
          'Metamagic',
          '4',
          '4',
          '4',
          '2',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '4th',
          '+2',
          '4',
          'Ability Score Improvement',
          '5',
          '5',
          '4',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['5th', '+3', '5', '', '5', '6', '4', '3', '2', '', '', '', '', '', ''],
        [
          '6th',
          '+3',
          '6',
          'Sorcerous Origin feature',
          '5',
          '7',
          '4',
          '3',
          '3',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '7th',
          '+3',
          '7',
          '',
          '5',
          '8',
          '4',
          '3',
          '3',
          '1',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '8th',
          '+3',
          '8',
          'Ability Score Improvement',
          '5',
          '9',
          '4',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
          '',
        ],
        [
          '9th',
          '+4',
          '9',
          '',
          '5',
          '10',
          '4',
          '3',
          '3',
          '3',
          '1',
          '',
          '',
          '',
          '',
        ],
        [
          '10th',
          '+4',
          '10',
          'Metamagic',
          '6',
          '11',
          '4',
          '3',
          '3',
          '3',
          '2',
          '',
          '',
          '',
          '',
        ],
        [
          '11th',
          '+4',
          '11',
          '',
          '6',
          '12',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        [
          '12th',
          '+4',
          '12',
          'Ability Score Improvement',
          '6',
          '12',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '',
          '',
          '',
        ],
        [
          '13th',
          '+5',
          '13',
          '',
          '6',
          '13',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        [
          '14th',
          '+5',
          '14',
          'Sorcerous Origin feature',
          '6',
          '13',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '',
          '',
        ],
        [
          '15th',
          '+5',
          '15',
          '',
          '6',
          '14',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        [
          '16th',
          '+5',
          '16',
          'Ability Score Improvement',
          '6',
          '14',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '',
        ],
        [
          '17th',
          '+6',
          '17',
          'Metamagic',
          '6',
          '15',
          '4',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '18th',
          '+6',
          '18',
          'Sorcerous Origin feature',
          '6',
          '15',
          '4',
          '3',
          '3',
          '3',
          '3',
          '1',
          '1',
          '1',
          '1',
        ],
        [
          '19th',
          '+6',
          '19',
          'Ability Score Improvement',
          '6',
          '15',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '1',
          '1',
          '1',
        ],
        [
          '20th',
          '+6',
          '20',
          'Sorcerous Restoration',
          '6',
          '15',
          '4',
          '3',
          '3',
          '3',
          '3',
          '2',
          '2',
          '1',
          '1',
        ],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Warlock',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      'Cantrips Known',
      'Spells Known',
      'Spell Slots',
      'Slot Level',
      'Invocations Known',
    ],
    anchorHeading: 'The Warlock',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Spells Spell Slot Invocations',
          'Known Slots Level Known',
          '1st +2 Otherworldly Patron, Pact',
          'Magic',
          '2nd +2 Eldritch Invocations',
          '3rd +2 Pact Boon',
          '4th +2 Ability Score Improvement',
          '5th +3',
          '6th +3 Otherworldly Patron feature',
          '7th +3',
          '8th +3 Ability Score Improvement',
          '9th +4',
          '10th +4 Otherworldly Patron feature',
          '11th +4 Mystic Arcanum (6th level)',
          '12th +4 Ability Score Improvement',
          '13th +5 Mystic Arcanum (7th level)',
          '14th +5 Otherworldly Patron feature',
          '15th +5 Mystic Arcanum (8th level)',
          '16th +5 Ability Score Improvement',
          '17th +6 Mystic Arcanum (9th level)',
          '18th +6',
          '19th +6 Ability Score Improvement',
          '20th +6 Eldritch Master',
          '2 2 1 1st',
          '2 3 2 1st 2',
          '2 4 2 2nd 2',
          '3 5 2 2nd 2',
          '3 6 2 3rd 3',
          '3 7 2 3rd 3',
          '3 8 2 4th 4',
          '3 9 2 4th 4',
          '3 10 2 5th 5',
          '4 10 2 5th 5',
          '4 11 3 5th 5',
          '4 11 3 5th 6',
          '4 12 3 5th 6',
          '4 12 3 5th 6',
          '4 13 3 5th 7',
          '4 13 3 5th 7',
          '4 14 4 5th 7',
          '4 14 4 5th 8',
          '4 15 4 5th 8',
          '4 15 4 5th 8',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          'Otherworldly Patron, Pact Magic',
          '2',
          '2',
          '1',
          '1st',
          '',
        ],
        ['2nd', '+2', 'Eldritch Invocations', '2', '3', '2', '1st', '2'],
        ['3rd', '+2', 'Pact Boon', '2', '4', '2', '2nd', '2'],
        ['4th', '+2', 'Ability Score Improvement', '3', '5', '2', '2nd', '2'],
        ['5th', '+3', '', '3', '6', '2', '3rd', '3'],
        ['6th', '+3', 'Otherworldly Patron feature', '3', '7', '2', '3rd', '3'],
        ['7th', '+3', '', '3', '8', '2', '4th', '4'],
        ['8th', '+3', 'Ability Score Improvement', '3', '9', '2', '4th', '4'],
        ['9th', '+4', '', '3', '10', '2', '5th', '5'],
        [
          '10th',
          '+4',
          'Otherworldly Patron feature',
          '4',
          '10',
          '2',
          '5th',
          '5',
        ],
        [
          '11th',
          '+4',
          'Mystic Arcanum (6th level)',
          '4',
          '11',
          '3',
          '5th',
          '5',
        ],
        ['12th', '+4', 'Ability Score Improvement', '4', '11', '3', '5th', '6'],
        [
          '13th',
          '+5',
          'Mystic Arcanum (7th level)',
          '4',
          '12',
          '3',
          '5th',
          '6',
        ],
        [
          '14th',
          '+5',
          'Otherworldly Patron feature',
          '4',
          '12',
          '3',
          '5th',
          '6',
        ],
        [
          '15th',
          '+5',
          'Mystic Arcanum (8th level)',
          '4',
          '13',
          '3',
          '5th',
          '7',
        ],
        ['16th', '+5', 'Ability Score Improvement', '4', '13', '3', '5th', '7'],
        [
          '17th',
          '+6',
          'Mystic Arcanum (9th level)',
          '4',
          '14',
          '4',
          '5th',
          '7',
        ],
        ['18th', '+6', '', '4', '14', '4', '5th', '8'],
        ['19th', '+6', 'Ability Score Improvement', '4', '15', '4', '5th', '8'],
        ['20th', '+6', 'Eldritch Master', '4', '15', '4', '5th', '8'],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Ranger',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      'Spells Known',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
    ],
    anchorHeading: 'The Ranger',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Proficiency',
          'Level Bonus Features',
          '1st +2 Favored Enemy, Natural Explorer',
        ],
        [
          'Spell Slots per Spell Level',
          'Spells Known 1st 2nd 3rd 4th 5th',
          '2nd +2 Fighting Style, Spellcasting',
          '3rd +2 Ranger Archetype, Primeval Awareness',
          '4th +2 Ability Score Improvement',
          '5th +3 Extra Attack',
          '6th +3 Favored Enemy and Natural Explorer improvements',
          '7th +3 Ranger Archetype feature',
          '8th +3',
          'Ability Score Improvement, Land s Stride',
          '9th +4',
          '10th +4 Natural Explorer improvement, Hide in Plain Sight',
          '11th +4 Ranger Archetype feature',
          '12th +4 Ability Score Improvement',
          '13th +5',
          '14th +5 Favored Enemy improvement, Vanish',
          '15th +5 Ranger Archetype feature',
          '16th +5 Ability Score Improvement',
          '17th +6',
          '18th +6 Feral Senses',
          '19th +6 Ability Score Improvement',
          '20th +6 Foe Slayer',
          '2 2',
          '3 3',
          '3 3',
          '4 4 2',
          '4 4 2',
          '5 4 3',
          '5 4 3',
          '6 4 3 2',
          '6 4 3 2',
          '7 4 3 3',
          '7 4 3 3',
          '8 4 3 3 1',
          '8 4 3 3 1',
          '9 4 3 3 2',
          '9 4 3 3 2',
          '10 4 3 3 3 1',
          '10 4 3 3 3 1',
          '11 4 3 3 3 2',
          '11 4 3 3 3 2',
        ],
      ],
      rows: [
        [
          '1st',
          '+2',
          'Favored Enemy, Natural Explorer',
          '',
          '',
          '',
          '',
          '',
          '',
        ],
        ['2nd', '+2', 'Fighting Style, Spellcasting', '2', '2', '', '', '', ''],
        [
          '3rd',
          '+2',
          'Ranger Archetype, Primeval Awareness',
          '3',
          '3',
          '',
          '',
          '',
          '',
        ],
        ['4th', '+2', 'Ability Score Improvement', '3', '3', '', '', '', ''],
        ['5th', '+3', 'Extra Attack', '4', '4', '2', '', '', ''],
        [
          '6th',
          '+3',
          'Favored Enemy and Natural Explorer improvements',
          '4',
          '4',
          '2',
          '',
          '',
          '',
        ],
        ['7th', '+3', 'Ranger Archetype feature', '5', '4', '3', '', '', ''],
        [
          '8th',
          '+3',
          'Ability Score Improvement, Land s Stride',
          '5',
          '4',
          '3',
          '',
          '',
          '',
        ],
        ['9th', '+4', '', '6', '4', '3', '2', '', ''],
        [
          '10th',
          '+4',
          'Natural Explorer improvement, Hide in Plain Sight',
          '6',
          '4',
          '3',
          '2',
          '',
          '',
        ],
        ['11th', '+4', 'Ranger Archetype feature', '7', '4', '3', '3', '', ''],
        ['12th', '+4', 'Ability Score Improvement', '7', '4', '3', '3', '', ''],
        ['13th', '+5', '', '8', '4', '3', '3', '1', ''],
        [
          '14th',
          '+5',
          'Favored Enemy improvement, Vanish',
          '8',
          '4',
          '3',
          '3',
          '1',
          '',
        ],
        ['15th', '+5', 'Ranger Archetype feature', '9', '4', '3', '3', '2', ''],
        [
          '16th',
          '+5',
          'Ability Score Improvement',
          '9',
          '4',
          '3',
          '3',
          '2',
          '',
        ],
        ['17th', '+6', '', '10', '4', '3', '3', '3', '1'],
        ['18th', '+6', 'Feral Senses', '10', '4', '3', '3', '3', '1'],
        [
          '19th',
          '+6',
          'Ability Score Improvement',
          '11',
          '4',
          '3',
          '3',
          '3',
          '2',
        ],
        ['20th', '+6', 'Foe Slayer', '11', '4', '3', '3', '3', '2'],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Monk',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Martial Arts',
      'Ki Points',
      'Unarmored Movement',
      'Features',
    ],
    anchorHeading: 'The Monk',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Level Proficiency Bonus Martial Arts Ki Points Unarmored Movement',
          '1st +2 1d4 — —',
        ],
        [
          'Features',
          'Unarmored Defense, Martial Arts',
          '2nd +2',
          '3rd +2',
          '4th +2',
          '5th +3',
          '6th +3',
          '7th +3',
          '8th +3',
          '9th +4',
          '10th +4',
          '11th +4',
          '12th +4',
          '13th +5',
          '14th +5',
          '15th +5',
          '16th +5',
          '17th +6',
          '18th +6',
          '19th +6',
          '20th +6',
          '1d4 2 +10 ft. Ki, Unarmored Movement',
          '1d4 3 +10 ft. Monastic Tradition, Deflect Missiles',
          '1d4 4 +10 ft. Ability Score Improvement, Slow Fall',
          '1d6 5 +10 ft. Extra Attack, Stunning Strike',
          '1d6 6 +15 ft. Ki-Empowered Strikes, Monastic Tradition feature',
          '1d6 7 +15 ft. Evasion, Stillness of Mind',
          '1d6 8 +15 ft. Ability Score Improvement',
          '1d6 9 +15 ft. Unarmored Movement improvement',
          '1d6 10 +20 ft. Purity of Body',
          '1d8 11 +20 ft. Monastic Tradition feature',
          '1d8 12 +20 ft. Ability Score Improvement',
          '1d8 13 +20 ft. Tongue of the Sun and Moon',
          '1d8 14 +25 ft. Diamond Soul',
          '1d8 15 +25 ft. Timeless Body',
          '1d8 16 +25 ft. Ability Score Improvement',
          '1d10 17 +25 ft. Monastic Tradition feature',
          '1d10 18 +30 ft. Empty Body',
          '1d10 19 +30 ft. Ability Score Improvement',
          '1d10 20 +30 ft. Perfect Self',
        ],
      ],
      rows: [
        ['1st', '+2', '1d4', '—', '—', 'Unarmored Defense, Martial Arts'],
        ['2nd', '+2', '1d4', '2', '+10 ft.', 'Ki, Unarmored Movement'],
        [
          '3rd',
          '+2',
          '1d4',
          '3',
          '+10 ft.',
          'Monastic Tradition, Deflect Missiles',
        ],
        [
          '4th',
          '+2',
          '1d4',
          '4',
          '+10 ft.',
          'Ability Score Improvement, Slow Fall',
        ],
        ['5th', '+3', '1d6', '5', '+10 ft.', 'Extra Attack, Stunning Strike'],
        [
          '6th',
          '+3',
          '1d6',
          '6',
          '+15 ft.',
          'Ki-Empowered Strikes, Monastic Tradition feature',
        ],
        ['7th', '+3', '1d6', '7', '+15 ft.', 'Evasion, Stillness of Mind'],
        ['8th', '+3', '1d6', '8', '+15 ft.', 'Ability Score Improvement'],
        ['9th', '+4', '1d6', '9', '+15 ft.', 'Unarmored Movement improvement'],
        ['10th', '+4', '1d6', '10', '+20 ft.', 'Purity of Body'],
        ['11th', '+4', '1d8', '11', '+20 ft.', 'Monastic Tradition feature'],
        ['12th', '+4', '1d8', '12', '+20 ft.', 'Ability Score Improvement'],
        ['13th', '+5', '1d8', '13', '+20 ft.', 'Tongue of the Sun and Moon'],
        ['14th', '+5', '1d8', '14', '+25 ft.', 'Diamond Soul'],
        ['15th', '+5', '1d8', '15', '+25 ft.', 'Timeless Body'],
        ['16th', '+5', '1d8', '16', '+25 ft.', 'Ability Score Improvement'],
        ['17th', '+6', '1d10', '17', '+25 ft.', 'Monastic Tradition feature'],
        ['18th', '+6', '1d10', '18', '+30 ft.', 'Empty Body'],
        ['19th', '+6', '1d10', '19', '+30 ft.', 'Ability Score Improvement'],
        ['20th', '+6', '1d10', '20', '+30 ft.', 'Perfect Self'],
      ],
    },
    expectedRows: 20,
  },
  {
    name: 'The Paladin',
    columns: [
      'Level',
      'Proficiency Bonus',
      'Features',
      '1st',
      '2nd',
      '3rd',
      '4th',
      '5th',
    ],
    anchorHeading: 'The Paladin',
    anchor: 'caption',
    headerLines: [],
    rows: {
      kind: 'class-progression-reconstruction',
      sourceBlocks: [
        [
          'Proficiency',
          'Level Bonus Features 1st',
          '1st +2 Divine Sense, Lay on Hands',
          '2nd +2 Fighting Style, Spellcasting, Divine Smite',
          '3rd +2 Divine Health, Sacred Oath',
          '4th +2 Ability Score Improvement',
        ],
        [
          'Spell Slots per Spell Level',
          '2nd 3rd 4th 5th',
          '2',
          '3',
          '3',
          '5th +3 Extra Attack',
          '6th +3 Aura of Protection',
          '7th +3 Sacred Oath feature',
          '8th +3 Ability Score Improvement',
          '9th +4',
          '10th +4 Aura of Courage',
          '11th +4 Improved Divine Smite',
          '12th +4 Ability Score Improvement',
          '13th +5',
          '14th +5 Cleansing Touch',
          '15th +5 Sacred Oath feature',
          '16th +5 Ability Score Improvement',
          '17th +6',
          '18th +6 Aura improvements',
          '19th +6 Ability Score Improvement',
          '20th +6 Sacred Oath feature',
          '4 2',
          '4 2',
          '4 3',
          '4 3',
          '4 3 2',
          '4 3 2',
          '4 3 3',
          '4 3 3',
          '4 3 3 1',
          '4 3 3 1',
          '4 3 3 2',
          '4 3 3 2',
          '4 3 3 3 1',
          '4 3 3 3 1',
          '4 3 3 3 2',
          '4 3 3 3 2',
        ],
      ],
      rows: [
        ['1st', '+2', 'Divine Sense, Lay on Hands', '', '', '', '', ''],
        [
          '2nd',
          '+2',
          'Fighting Style, Spellcasting, Divine Smite',
          '2',
          '',
          '',
          '',
          '',
        ],
        ['3rd', '+2', 'Divine Health, Sacred Oath', '3', '', '', '', ''],
        ['4th', '+2', 'Ability Score Improvement', '3', '', '', '', ''],
        ['5th', '+3', 'Extra Attack', '4', '2', '', '', ''],
        ['6th', '+3', 'Aura of Protection', '4', '2', '', '', ''],
        ['7th', '+3', 'Sacred Oath feature', '4', '3', '', '', ''],
        ['8th', '+3', 'Ability Score Improvement', '4', '3', '', '', ''],
        ['9th', '+4', '', '4', '3', '2', '', ''],
        ['10th', '+4', 'Aura of Courage', '4', '3', '2', '', ''],
        ['11th', '+4', 'Improved Divine Smite', '4', '3', '3', '', ''],
        ['12th', '+4', 'Ability Score Improvement', '4', '3', '3', '', ''],
        ['13th', '+5', '', '4', '3', '3', '1', ''],
        ['14th', '+5', 'Cleansing Touch', '4', '3', '3', '1', ''],
        ['15th', '+5', 'Sacred Oath feature', '4', '3', '3', '2', ''],
        ['16th', '+5', 'Ability Score Improvement', '4', '3', '3', '2', ''],
        ['17th', '+6', '', '4', '3', '3', '3', '1'],
        ['18th', '+6', 'Aura improvements', '4', '3', '3', '3', '1'],
        ['19th', '+6', 'Ability Score Improvement', '4', '3', '3', '3', '2'],
        ['20th', '+6', 'Sacred Oath feature', '4', '3', '3', '3', '2'],
      ],
    },
    expectedRows: 20,
  },
];

/**
 * All class-chapter progression and feature-owned tables emitted by
 * `parseDocumentTables` (eshyra-4a7.6). Spread into
 * `SRD_5_1_DOCUMENT_TABLE_SPECS`; the Barbarian table stays defined inline
 * there as the canonical single-line-per-row example.
 */
export const CLASS_PROGRESSION_TABLE_SPECS: readonly DocumentTableSpec[] = [
  ...FIGHTER_AND_ROGUE_SPECS,
  ...FEATURE_OWNED_TABLE_SPECS,
  ...RECONSTRUCTED_CLASS_PROGRESSION_SPECS,
];
